name: auto release

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: self-hosted

    steps:
      - run: ipfs
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn --version
